### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by ljl7123** [christopher-wolff23/Laser_Tanks3#8]
@christopher-wolff23 , could you clarify the following questions about the application:
1. What is the purpose of the application?
2. Who is the audience?

Thanks!

**Comment by christopher-wolff23** [comment]
1. It's a video game! Entertainment. Blowing up tanks. 
2. Whoever likes video games. I imagine the finished game would be considered pretty kid-friendly. Not any real violence. 

Have you tried running the game? I think you can run either of the .exe files in the repo and be good to go. Let me know if you have any questions.
